spring.application.name=user-service

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://config-server:8888

management.endpoints.web.exposure.include=refresh

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest






# Keycloak Admin
keycloak.server-url=http://localhost:8080
keycloak.realm=EcommerceRealm
keycloak.admin-client-id=admin-cli
keycloak.admin-username=admin
keycloak.admin-password=admin
keycloak.gateway-client-id=gateway
