spring.application.name=config-server
server.port=8888

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server native mode
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/config


