server.port=8086

welcome.message=Welcome to payment-service from Config Server

# MongoDB Atlas (Cloud) - Active
spring.data.mongodb.uri=mongodb+srv://ademchebbi145_db_user:GhAAQCAXxUgNj1hC@paymentdb.qlptabh.mongodb.net/payment_db?retryWrites=true&w=majority

# Local MongoDB - Backup option
#spring.data.mongodb.uri=mongodb://localhost:27017/payment_db

# Keycloak OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/EcommerceRealm
